name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Пушим в главную ветку, чтобы запускался процесс

jobs:
  ci:
    runs-on: ubuntu-latest  # Окружение для запуска CI

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Клонирование репозитория

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Настройка Docker Buildx для мульти-архитектурных сборок

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Логин в Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest .  # Сборка Docker образа

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest  # Публикация образа на Docker Hub

  cd:
    runs-on: ubuntu-latest  # Окружение для запуска CD

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Клонирование репозитория

      - name: Pull Docker image from Docker Hub
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest  # Скачивание Docker образа из Docker Hub

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest  # Запуск контейнера на порту 5000
