name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Archive HTML page
        uses: montudor/action-zip@v1
        with:
          args: "zip -r archive.zip task.html"

      - name: Upload to GitHub Packages
        uses: actions/upload-artifact@v4
        with:
          name: epam-Maksim-ci-easyplus
          path: archive.zip
