name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Archive HTML page
        uses: montudor/action-zip@v1
        with:
          args: "zip -r archive.zip task.html"

      - name: Create GitHub Release
        uses: actions/create-release@v1.1.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: epam-Maksim-ci-easy
          draft: false
          prerelease: false
          assets: archive.zip
