name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Archive HTML page
        run: zip -r archive.zip task.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: archive
          path: archive.zip  

